import {
  CursorArrowRaysIcon,
  EnvelopeOpenIcon,
  UsersIcon,
  CurrencyDollarIcon,
  VideoCameraIcon,
} from '@heroicons/react/24/outline'

export const stats = [
  {
    id: 1,
    name: 'Spend',
    stat: '1283',
    icon: CurrencyDollarIcon,
    change: '122',
    changeType: 'increase',
  },
  {
    id: 2,
    name: 'Clicks',
    stat: '1092',
    icon: CursorArrowRaysIcon,
    change: '202',
    changeType: 'increase',
  },
  {
    id: 3,
    name: 'Views',
    stat: '12909',
    icon: VideoCameraIcon,
    change: '1012',
    changeType: 'increase',
  },
  {
    id: 4,
    name: 'CPM',
    stat: '58.16%',
    icon: EnvelopeOpenIcon,
    change: '5.4%',
    changeType: 'increase',
  },
  {
    id: 5,
    name: 'CTR',
    stat: '4.57%',
    icon: UsersIcon,
    change: '.2%',
    changeType: 'decrease',
  },
  {
    id: 6,
    name: 'CPC',
    stat: '$.42',
    icon: CursorArrowRaysIcon,
    change: '.03',
    changeType: 'increase',
  },
]
export const campaignStubData = [
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 1250,
    description: 'Accounting made simple for small businesses.',
    pid: 'abcdefgh',
    target: 'https://tincre.dev/promo',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://res.cloudinary.com/tincre/image/upload/v1666907624/tailwindui-salient/taxpal-og_xka3ix_q4ulfc.webp',
    stats: stats,
  },
  // More people...
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 3500,
    description: 'Accounting made simple for small businesses.',
    pid: 'defghijk',
    target: 'https://tincre.dev/promo',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60',
    stats: stats,
  },
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 1000,
    description: 'Accounting made simple for small businesses.',
    pid: 'efghijkl',
    target: 'https://tincre.dev/promo',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:

      'https://res.cloudinary.com/tincre/image/upload/v1666907673/tailwindui-salient/background-faqs_nugiew_m0skue.webp',
    stats: stats,
  },
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 18150,
    description: 'Accounting made simple for small businesses.',
    pid: 'fghijklm',
    target: 'https://tincre.dev/promo',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://res.cloudinary.com/tincre/image/upload/v1666907587/tailwindui-salient/screenshots/vat-returns_uhkad6_c8tze2.webp',
    stats: stats,
  },
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 8725,
    description: 'Accounting made simple for small businesses.',
    pid: 'bcdefghi',
    target: 'https://tincre.dev/promo',

    currency: 'USD',
    isActive: false,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://res.cloudinary.com/tincre/image/upload/v1666907624/tailwindui-salient/taxpal-og_xka3ix_q4ulfc.webp',
    stats: stats,
  },
  {
    name: 'Jane Cooper',
    adTitle: 'Easier taxes 👉️ taxpal.com',
    budget: 250,
    description: 'Accounting made simple for small businesses.',
    pid: 'cdefghij',
    target: 'https://tincre.dev/promo',

    currency: 'USD',
    isActive: false,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Accounting made simple and illegal for small businesses.',
    adCallToAction: "🤞 Don't get audited!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    imageUrl:
      'https://res.cloudinary.com/tincre/image/upload/v1666907624/tailwindui-salient/taxpal-og_xka3ix_q4ulfc.webp',
    stats: stats,
  },
]
