import {
  CursorArrowRaysIcon,
  EnvelopeOpenIcon,
  UsersIcon,
  CurrencyDollarIcon,
  VideoCameraIcon,
} from '@heroicons/react/24/outline';

import {
  generateSpend,
  generateClicks,
  generateViews,
  generateCPC,
  generateCPM,
  generateCTR,
} from './lib/gen-data';
const demo1dates = [
  '2023-03-15',
  '2023-03-16',
  '2023-03-17',
  '2023-03-18',
  '2023-03-19',
  '2023-03-20',
  '2023-03-21',
  '2023-03-22',
  '2023-03-23',
  '2023-03-24',
  '2023-03-25',
  '2023-03-26',
  '2023-03-27',
].reverse();
const demo2dates = [
  '2023-03-10',
  '2023-03-11',
  '2023-03-12',
  '2023-03-13',
  '2023-03-14',
  '2023-03-15',
  '2023-03-16',
  '2023-03-17',
  '2023-03-18',
  '2023-03-19',
  '2023-03-20',
  '2023-03-21',
  '2023-03-22',
].reverse();
const demo3dates = [
  '2023-02-10',
  '2023-02-11',
  '2023-02-12',
  '2023-02-13',
  '2023-02-14',
  '2023-02-15',
  '2023-02-16',
  '2023-02-17',
  '2023-02-18',
  '2023-02-19',
  '2023-02-20',
  '2023-02-21',
  '2023-02-22',
].reverse();
const demo4dates = [
  '2022-12-10',
  '2022-12-11',
  '2022-12-12',
  '2022-12-13',
  '2022-12-14',
  '2022-12-15',
  '2022-12-16',
  '2022-12-17',
  '2022-12-18',
  '2022-12-19',
  '2022-12-20',
  '2022-12-21',
  '2022-12-22',
].reverse();

export const campaignStubData = [
  {
    name: 'Jane Cooper',
    adTitle: '🆕 music from The Word Alive',
    receiptId: 'ijklmnopqr4242',
    budget: '$1450',
    description: 'Accounting made simple for small businesses.',
    pid: 'abcdefgh',
    target:
      'https://open.spotify.com/track/1Y5jDuVd6djgjTn5UetTxm?si=769f3c6b78bc4bf3',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: 'Listen to a new chapter, "Nocturnal Future" OUT NOW',
    adCallToAction: 'Stream new music from The Word Alive',
    buttonText: 'Listen now',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672885636/undrcvr-ads.com/Ad%20Mockups/TWA_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '$1283',
        icon: CurrencyDollarIcon,
        change: '122',
        changeType: 'increase',
        chartData: {
          labels: demo1dates,
          data: generateSpend(1283 - 122, 1283, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '1092',
        icon: CursorArrowRaysIcon,
        change: '202',
        changeType: 'increase',
        chartData: {
          labels: demo1dates,
          data: generateClicks(1092 - 202, 1092, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '12909',
        icon: VideoCameraIcon,
        change: '1012',
        changeType: 'increase',
        chartData: {
          data: generateViews(12909 - 1012, 12909).reverse(),
          labels: demo1dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$5.16',
        icon: EnvelopeOpenIcon,
        change: '$.4',
        changeType: 'increase',
        chartData: {
          data: generateCPM(5.16 - 0.4, 5.16).reverse(),
          labels: demo1dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '4.57%',
        icon: UsersIcon,
        change: '.2%',
        changeType: 'decrease',
        chartData: {
          data: generateCTR(4.57 + 0.2, 4.57).reverse(),
          labels: demo1dates,
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$.03',
        icon: CursorArrowRaysIcon,
        change: '.01',
        changeType: 'decrease',
        chartData: {
          data: generateCPC(0.03 + 0.01, 0.03).reverse(),
          labels: demo1dates,
        },
      },
    ],
  },
  // More people...
  {
    name: 'The Revel',
    adTitle: 'NYC The Revel is coming for you!',
    budget: '$3500',
    description:
      'Accounting made fun and questionably legal for small businesses.',
    pid: 'defghijk',
    target: 'https://www.nevertoodifferent.com/shows',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy: '❗️JANUARY 5th❗️We will be live at Mercury Lounge with SAVOIA',
    adCallToAction: 'Get your tickets before they sell out!',
    buttonText: 'Buy now',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672886927/undrcvr-ads.com/Ad%20Mockups/The_Revel_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '$2892',
        icon: CurrencyDollarIcon,
        change: '74',
        changeType: 'increase',
        chartData: {
          labels: demo2dates,
          data: generateSpend(2892 - 74, 2892, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '11593',
        icon: CursorArrowRaysIcon,
        change: '121',
        changeType: 'increase',
        chartData: {
          labels: demo2dates,
          data: generateClicks(11593 - 121, 11593, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '312909',
        icon: VideoCameraIcon,
        change: '3491',
        changeType: 'increase',
        chartData: {
          data: generateViews(132909 - 3491, 132909).reverse(),
          labels: demo2dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$4.16',
        icon: EnvelopeOpenIcon,
        change: '$.54',
        changeType: 'decrease',
        chartData: {
          data: generateCPM(4.16 + 0.54, 4.16).reverse(),
          labels: demo2dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '6.71%',
        icon: UsersIcon,
        change: '.2%',
        changeType: 'increase',
        chartData: {
          data: generateCTR(6.71 - 0.2, 6.71).reverse(),
          labels: demo2dates,
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$.42',
        icon: CursorArrowRaysIcon,
        change: '.01',
        changeType: 'decrease',
        chartData: {
          data: generateCPC(0.42 + 0.01, 0.42).reverse(),
          labels: demo2dates,
        },
      },
    ],
  },
  {
    name: 'Token',
    adTitle: 'Book your VIP tix',
    budget: '$1000',
    description: 'Lock in your VIP spot before they are sold out',
    pid: 'efghijkl',
    target: 'https://www.nevertoodifferent.com/shows',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy:
      "I can't wait for this tour!!! The VIP experience will be next level!",
    adCallToAction: '🎟️ Get your VIP upgrade now',
    buttonText: 'Learn more',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672886370/undrcvr-ads.com/Ad%20Mockups/Token_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '$6',
        icon: CurrencyDollarIcon,
        change: '$6',
        changeType: 'increase',
        chartData: {
          labels: demo3dates,
          data: generateSpend(0, 6, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '0',
        icon: CursorArrowRaysIcon,
        change: '0',
        changeType: 'increase',
        chartData: {
          labels: demo3dates,
          data: generateSpend(0, 0, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '16',
        icon: VideoCameraIcon,
        change: '16',
        changeType: 'increase',
        chartData: {
          data: generateViews(16 - 16, 16).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$12.16',
        icon: EnvelopeOpenIcon,
        change: '$2.1',
        changeType: 'decrease',
        chartData: {
          data: generateCPM(12.16 + 2.1, 12.16).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '1.84%',
        icon: UsersIcon,
        change: '.5%',
        changeType: 'increase',
        chartData: {
          data: generateCTR(1.84 - 0.5, 1.84).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$.14',
        icon: CursorArrowRaysIcon,
        change: '.02',
        changeType: 'decrease',
        chartData: {
          data: generateCPC(0.14 + 0.02, 0.14).reverse(),
          labels: demo3dates,
        },
      },
    ],
  },
  {
    name: 'Pop Evil',
    adTitle: 'SKELETONS TOUR on sale now',
    budget: '$18150',
    description: 'Accounting made simple for small businesses.',
    pid: 'fghijklm',
    target: 'https://popevil.com',
    currency: 'USD',
    isActive: true,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy:
      'The time has come for SKELETONS TOUR! Get your tickets before they sell out! Find your city + tickets and VIP.',
    adCallToAction: 'Get your tix today!',
    buttonText: 'Learn more',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672886628/undrcvr-ads.com/Ad%20Mockups/Pop_Evil_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '$7283',
        icon: CurrencyDollarIcon,
        change: '322',
        changeType: 'increase',
        chartData: {
          labels: demo3dates,
          data: generateSpend(7283 - 322, 7283, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '1092',
        icon: CursorArrowRaysIcon,
        change: '202',
        changeType: 'increase',
        chartData: {
          labels: demo3dates,
          data: generateClicks(1092 - 202, 1092, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '12909',
        icon: VideoCameraIcon,
        change: '1012',
        changeType: 'increase',
        chartData: {
          data: generateViews(12909 - 1012, 12909).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$5.10',
        icon: EnvelopeOpenIcon,
        change: '$3.1',
        changeType: 'increase',
        chartData: {
          data: generateCPM(5.1 - 3.1, 5.1).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '3.33%',
        icon: UsersIcon,
        change: '.3%',
        changeType: 'decrease',
        chartData: {
          data: generateCTR(3.33 + 0.3, 3.33).reverse(),
          labels: demo3dates,
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$1.25',
        icon: CursorArrowRaysIcon,
        change: '.03',
        changeType: 'decrease',
        chartData: {
          data: generateCPC(1.25 + 0.03, 1.25).reverse(),
          labels: demo3dates,
        },
      },
    ],
  },
  {
    name: 'All That Remains',
    adTitle: '48H Merch Sale!',
    budget: '$8725',
    description: 'Accounting made simple for small businesses.',
    pid: 'bcdefghi',
    target: 'https://allthatremainsonline.com',

    currency: 'USD',
    isActive: false,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy:
      '⏩️ We’re skipping straight to Black Friday this year. Snatch up storewide discounts on EVERYTHING',
    adCallToAction: "Get it before it's gone!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672887151/undrcvr-ads.com/Ad%20Mockups/All_ThatLRemains_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '$8725',
        icon: CurrencyDollarIcon,
        change: '219',
        changeType: 'increase',
        chartData: {
          labels: demo4dates,
          data: generateSpend(8725 - 219, 8725, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '21944',
        icon: CursorArrowRaysIcon,
        change: '421',
        changeType: 'increase',
        chartData: {
          labels: demo4dates,
          data: generateClicks(21944 - 421, 21944, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '62909',
        icon: VideoCameraIcon,
        change: '5042',
        changeType: 'increase',
        chartData: {
          data: generateViews(62909 - 5042, 62090).reverse(),
          labels: demo4dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$2.50',
        icon: EnvelopeOpenIcon,
        change: '$.05',
        changeType: 'increase',
        chartData: {
          data: generateCPM(2.5 - 0.05, 2.5).reverse(),
          labels: demo4dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '4.17%',
        icon: UsersIcon,
        change: '.4%',
        changeType: 'decrease',
        chartData: {
          labels: demo4dates,
          data: generateCTR(0.02, 0.04, 13).reverse(),
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$.51',
        icon: CursorArrowRaysIcon,
        change: '.13',
        changeType: 'increase',
        chartData: {
          data: generateCPC(0.51 - 0.13, 0.51).reverse(),
          labels: demo4dates,
        },
      },
    ],
  },
  {
    name: 'All That Remains',
    adTitle: '48H Merch Sale!',
    budget: '$8725',
    description: 'Accounting made simple for small businesses.',
    pid: 'bcdefghi',
    target: 'https://allthatremainsonline.com',

    currency: 'USD',
    isActive: false,
    title: 'Paradigm Representative',
    role: 'Admin',
    email: 'janecooper@example.com',
    adCopy:
      '🔥 F*ck it… we’re skipping straight to Black Friday this year. Snatch up this mystery box ⁉️PLUS storewide discounts',
    adCallToAction: "Get it before it's gone!",
    buttonText: 'Sign up',
    telephone: '+1-202-555-0170',
    creativeUrls: [
      'https://res.cloudinary.com/tincre/image/upload/v1672887151/undrcvr-ads.com/Ad%20Mockups/All_ThatLRemains_1.webp',
    ],
    stats: [
      {
        id: 1,
        name: 'Spend',
        stat: '250',
        icon: CurrencyDollarIcon,
        change: '9',
        changeType: 'increase',
        chartData: {
          labels: demo4dates,
          data: generateSpend(250 - 9, 250, 13).reverse(),
        },
      },
      {
        id: 2,
        name: 'Clicks',
        stat: '451',
        icon: CursorArrowRaysIcon,
        change: '20',
        changeType: 'increase',
        chartData: {
          labels: demo4dates,
          data: generateClicks(451 - 20, 451, 13).reverse(),
        },
      },
      {
        id: 3,
        name: 'Views',
        stat: '0',
        icon: VideoCameraIcon,
        change: '0',
        changeType: 'increase',
        chartData: {
          data: generateViews(0, 0).reverse(),
          labels: demo4dates,
        },
      },
      {
        id: 4,
        name: 'CPM',
        stat: '$5.42',
        icon: EnvelopeOpenIcon,
        change: '$.30',
        changeType: 'increase',
        chartData: {
          data: generateCPM(6.29 - 0.3, 6.29).reverse(),
          labels: demo4dates,
        },
      },
      {
        id: 5,
        name: 'CTR',
        stat: '3.57%',
        icon: UsersIcon,
        change: '.3%',
        changeType: 'decrease',
        chartData: {
          data: generateCTR(3.57 + 0.3, 3.57).reverse(),
          labels: demo4dates,
        },
      },
      {
        id: 6,
        name: 'CPC',
        stat: '$.16',
        icon: CursorArrowRaysIcon,
        change: '.03',
        changeType: 'increase',
        chartData: {
          data: generateCPC(0.16 - 0.03, 0.16).reverse(),
          labels: demo4dates,
        },
      },
    ],
  },
];
