import type { NextPage } from 'next';
import Head from 'next/head';
import { Thing } from '../../../dist/promo-dashboard.esm.js';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Promo Button Demo</title>
        <meta
          name="description"
          content="Generated by create next app, by Tincre, for Promo Dashboard users."
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">
          Welcome to the <a href="https://tincre.dev/promo">Promo Dashboard</a>{' '}
          demo!
        </h1>
        <div style={{ textAlign: 'center', marginTop: '20px' }}>
          <Thing />
          <p style={{ marginTop: '20px', marginBottom: '10px' }}>
            <code>npm install @tincre/promo-dashboard</code>
          </p>
          <p
            className=""
            style={{
              marginTop: '2rem',
              marginBottom: '2rem',
              fontWeight: 'bold',
              marginLeft: 'auto',
              marginRight: 'auto',
              textAlign: 'center',
            }}
          >
            <a
              target="_blank"
              rel="noreferrer noopener"
              href="https://tincre.dev/docs"
            >
              Read the docs
            </a>
          </p>
          <p
            className=""
            style={{
              marginTop: '2rem',
              marginBottom: '2rem',
              fontWeight: 'bold',
              marginLeft: 'auto',
              marginRight: 'auto',
              textAlign: 'center',
            }}
          >
            <a
              target="_blank"
              rel="noreferrer noopener"
              href="https://community.tincre.dev/c/promo-button"
            >
              Abuse your community
            </a>
          </p>
        </div>

        <p className="">
          Get started by editing <code className="">pages/index.tsx</code>
        </p>

        <div className="">
          <a href="https://nextjs.org/docs" className="">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className=""
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className=""
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="">
        <a
          href="https://tincre.com"
          target="_blank"
          className="hover:text-gray-900 text-gray-700 hover:underline"
          rel="noreferrer"
        >
          Tincre
        </a>
      </footer>
    </div>
  );
};

export default Home;
